### PR TITLE
Using anki configuration

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
Hi,

This PR started because of https://github.com/Arthur-Milchior/anki-export-from-browser/issues/6#event-2979150170
Your addon conflict with mine. And it seems that some users actually don't use the export part. So I removed it, and hope it can be in another add-on, so that it separates the conflicting part and the non conflicting part.
I put the list of fields, and some other thing, in anki configuration field. So that you don't have to restart anki each time there is a change.
In case of absence of answer from you, i'll upload it in one week on ankiweb

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
Any news ? 
@ankingmed told me you're up for merging it. Is it right

**Comment by AnKingMed** [comment]
He’s on his surgery rotation at the moment (likely working 80+ hours/week) so it may take a couple days for him to make the change

**Comment by johnpincock** [comment]
Hi Arthur, Thanks for all your help! I've done it today. Sorry for my slowness, I've been caught up a fair bit over the last 5 weeks but should be free from now! I'll be back on comms and have made your version the master version as I think suits the needs of Anki users better.

**Comment by Arthur-Milchior** [comment]
No trouble for me. I don't expect to use this add-on. It's anKing's users which have to wait
I don't know whether you used my version of the work here. I don't really understand why you didn't accept this pull request. Did you made anything different from what was in my code ?
Accepting my PR seems better as far as I can tell, because it allows to keep git history. Which may be useful to anyone wanting to work on this add-on later.

**Comment by AnKingMed** [comment]
As far as I can tell the last version @Arthur-Milchior sent me and the current version on here match identically.. what are the conflicts in this pull request? I want to make sure everything looks ok before going public with it

**Comment by johnpincock** [comment]
Yeah it's the same, sorry I'm just getting my head around using git ! - I'll accept your PR as soon as I can, to preserve the git history, but just for the time being they are the very same

**Comment by AnKingMed** [comment]
Cool! I don't understand Git as well either so I just wanted to make sure:)  Thanks for everything!

**Comment by Arthur-Milchior** [comment]
A pull request essentially says either : here is a list of new files N. And, in existing file A replace lines containing the text B by C.
If N already exists and A does not contain B, the pull request can t be applied amymore. That would be the case if johnpicock added the files of my repo in his

**Comment by johnpincock** [comment]
Got it, so has this worked okay now ? I realise now about accepting the pull request in future, but  is the merge okay?

**Comment by Arthur-Milchior** [comment]
It seems to be, thank you. A little bit unusual they way it is, but at least anyone wanting to update this code later will still have the comments of each commit of my git repo

**Pull request merged**
