### PR TITLE
Stop disabling new APKG importer

### PR DESCRIPTION
**Pull request by abdnh**
See https://forums.ankiweb.net/t/import-files-even-after-newest-update/41959/12

This reverts the change made in #33 and instead make the add-on show a message if the legacy import/export handling option is not enabled.

image

@AnKingMed

### CODE REVIEW

**Comment by AnKingMed** [comment]
Should we also add something like 

"This may make it so you cannot import newer files. If you experience errors, turn this setting off temporarily"

Or something like that?

**Comment by abdnh** [comment]
Good point. I added that.

**Comment by AnKingMed** [comment]
Looks good to me! Can you upload it @abdnh?

**Comment by abdnh** [comment]
Uploaded.

**Pull request merged**
